spring:
  application:
    name: insta-auth

  data:
    mongodb:
      database: instaclone_auth

server:
  port: 9000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      
security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey