spring:
  application:
    name: instaclone-auth

  data:
    mongodb:
      database: instaclone_auth

server:
  port: 9000

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey