spring:
  application:
    name: insta-auth

  data:
    mongodb:
      database: instaclone_auth

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        momentsUserChanged:
          destination: moments.user.changed
          contentType: application/json
server:
  port: 9000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      
security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey