spring:
  application:
    name: insta-graph

  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: admin

server:
  port: 8002

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey